version: '3.9'
services:
  app1:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - app/.env

  app2:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - app/.env

  app3:
    build: .
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    env_file:
      - app/.env